//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoachDBEntities1 : DbContext
    {
        public CoachDBEntities1()
            : base("name=CoachDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
